# Generated by Django 5.2.1 on 2025-05-25 21:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('ultima_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=20, unique=True)),
                ('data_nascimento', models.DateField()),
                ('endereco', models.CharField(blank=True, max_length=255, null=True)),
                ('telefone', models.CharField(blank=True, max_length=15, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Aluno',
                'verbose_name_plural': 'Alunos',
                'db_table': 'aluno',
            },
        ),
        migrations.CreateModel(
            name='Enquete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('data_inicio', models.DateTimeField()),
                ('data_fim', models.DateTimeField()),
                ('criador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enquetes_criadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Enquete',
                'verbose_name_plural': 'Enquetes',
                'get_latest_by': 'data_criacao',
            },
        ),
        migrations.CreateModel(
            name='Questao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_questao', models.CharField(max_length=255)),
                ('tipo_questao', models.CharField(choices=[('texto', 'Texto'), ('multipla_escolha', 'Múltipla Escolha'), ('unica_escolha', 'Única Escolha')], max_length=50)),
                ('ordem', models.IntegerField(default=0)),
                ('ativa', models.BooleanField(default=True)),
                ('enquete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enquetes.enquete')),
            ],
            options={
                'verbose_name': 'Questão',
                'verbose_name_plural': 'Questões',
                'unique_together': {('enquete', 'ordem')},
            },
        ),
        migrations.CreateModel(
            name='OpcaoResposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_opcao', models.CharField(max_length=200)),
                ('contador_votos', models.IntegerField(default=0)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enquetes.questao')),
            ],
            options={
                'verbose_name': 'Opção de Resposta',
                'verbose_name_plural': 'Opções de Resposta',
                'ordering': ['texto_opcao'],
            },
        ),
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_resposta', models.DateTimeField(auto_now_add=True)),
                ('identificador_anonimo', models.CharField(blank=True, max_length=100, null=True)),
                ('finalizada', models.BooleanField(default=False)),
                ('aluno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='enquetes.aluno')),
                ('enquete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enquetes.enquete')),
            ],
            options={
                'verbose_name': 'Resposta',
                'verbose_name_plural': 'Respostas',
            },
        ),
        migrations.CreateModel(
            name='ItemResposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_resposta', models.TextField(blank=True, null=True)),
                ('data_resposta_item', models.DateTimeField(auto_now_add=True)),
                ('opcao_selecionada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='enquetes.opcaoresposta')),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enquetes.questao')),
                ('resposta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enquetes.resposta')),
            ],
            options={
                'verbose_name': 'Item de Resposta',
                'verbose_name_plural': 'Itens de Resposta',
            },
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('ano_letivo', models.IntegerField()),
                ('semestre', models.IntegerField()),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enquetes.curso')),
                ('professor_responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Turma',
                'verbose_name_plural': 'Turmas',
            },
        ),
        migrations.AddField(
            model_name='aluno',
            name='turmas',
            field=models.ManyToManyField(to='enquetes.turma'),
        ),
        migrations.AddConstraint(
            model_name='resposta',
            constraint=models.UniqueConstraint(fields=('enquete', 'aluno'), name='unique_enquete_aluno_resposta'),
        ),
        migrations.AddIndex(
            model_name='itemresposta',
            index=models.Index(fields=['resposta', 'questao'], name='resp_quest_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='itemresposta',
            unique_together={('resposta', 'questao')},
        ),
        migrations.AlterUniqueTogether(
            name='turma',
            unique_together={('curso', 'ano_letivo', 'semestre')},
        ),
    ]
